### ISSUE TITLE
It says "Call to undefined function imageantialias()"

### ISSUE THREAD

**Issue by algobasket** [timovn/identicon#1]
It says "Call to undefined function imageantialias()"
Im using latest PHP on Elementary OS (Debian based)

**Comment by timovn** [comment]
It seems to be cause by the way how PHP was compiled.

> Note: This function is only available if PHP is compiled with the bundled version of the GD library.
(https://stackoverflow.com/questions/5756144/imageantialias-call-to-undefined-function-error-with-gd-installed)

… which seems to be the case on Debian (but not on Ubuntu and derivatives, since I don’t have the problem on Linux Mint).

I don’t have any fix in mind, however, this function is only here to accelerate the making of the images. It might still work if you simply comment the lines out.

**Comment by algobasket** [comment]
Ok Thanks
